---
version: "3.7"
networks:
 ansible:
   driver: bridge
services:
  ansible:
   container_name: ansible
   image: guiprison:1.0
   volumes:
      - type: bind
        source: ./
        target: /tmp/playbook
   ports:
    - "8080:8080"
   networks:
    - ansible
   environment:
    - ANSIBLE_CONFIG=/tmp/playbook/src/ansible.cfg
volumes:
  ansible:
...