- name: Demo create instance
  hosts: localhost
  gather_facts: yes
  vars_files:
    - /tmp/playbook/src/demo/gcp_auth.yml
    - /tmp/playbook/src/demo/gcp_zones.yml
  tasks:
  - name: create a managed zone
    gcp_dns_managed_zone:
      name: "{{ item.name }}"
      dns_name: "{{ item.dns }}"
      description: Ansible created
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_auth_kind }}"
      service_account_file: "{{ gcp_credentials_file }}"
      state: present
    loop:
      - { name: 'prod', dns: 'ansible.demo.com.' }
      - { name: 'stage', dns: 'stage.ansible.demo.com.' }